services:
  ergogen:
    image: keebs/ergogen
    build:
      pull: true
      args:
        - UID
        - GID
      dockerfile_inline: |
        FROM node
        WORKDIR /app
        RUN npm install -g ergogen
        ARG UID GID
        RUN addgroup --gid ${GID} user || adduser --uid ${UID} --gid ${GID} user || true
        USER ${UID}:${GID}
        WORKDIR /config
        ENTRYPOINT ["ergogen"]
